from flaskr_v1 import app
from flask import render_template


@app.route('/')
def index():
    """
    books = [
        {'title': '初級編',
         'price': '易しい問題が出るよ！',},
        {'title': '中級編',
         'price': '少しむずかしいかも！',},
        {'title': '上級編',
         'price': 'わかったらすごい！',},
    ]
    """
    return render_template(
        'index.html',
        #books=books
    )

@app.route('/form')
def form():
    books = [
        {'daimei': '第１問',
         'mondai': '国境の長いトンネルを抜けると雪国であった。夜の底が白くなった。信号所に汽車が止まった。',
         'sentakusi1': '太宰治「人間失格」',
         'sentakusi2': '三島由紀夫「金閣寺」',
         'sentakusi3': '川端康成「雪国」',
         'sentakusi4': '芥川龍之介「地獄変」',
         'kotae': 'answer3',
         'ID': 1,},
        {'daimei': '第２問',
         'mondai': 'メロスは激怒した。必ず、かの邪智暴虐の王を除かなければならぬと決意した。メロスには政治がわからぬ。',
         'sentakusi1': '湊かなえ「告白」',
         'sentakusi2': '太宰治「走れメロス」',
         'sentakusi3': '三島由紀夫「三島由紀夫レター教室」',
         'sentakusi4': '東野圭吾「秘密」',
         'kotae': 'answer2',
         'ID' : 2,},
        {'daimei': '第３問',
         'mondai': 'どっどど どどうど どどうど どどう 青いくるみも吹きとばせ すっぱいかりんも吹きとばせ どっどど どどうど どどうど どどう',
         'sentakusi1': '芥川龍之介「鼻」',
         'sentakusi2': '梶井基次郎「檸檬」',
         'sentakusi3': '中島敦「山月記」',
         'sentakusi4': '宮沢賢治「風の又三郎」',
         'kotae': 'answer4',
         'ID' : 3,},
        {'daimei': '第４問',
         'mondai': '春が二階から落ちてきた。私がそう言うと、聞いた相手は大抵、嫌な顔をする。気取った言い回しだと避難し、奇をてらった比喩だと勘違いをする。',
         'sentakusi1': '村上春樹「風の歌を聴け」',
         'sentakusi2': '太宰治「晩年」',
         'sentakusi3': '伊坂幸太郎「重力ピエロ」',
         'sentakusi4': '夏目漱石「吾輩は猫である」',
         'kotae': 'answer4',
         'ID' : 4,},
        {'daimei': '第５問',
         'mondai': 'アレクセイ・フョードロウィチ・カラマーゾフは、今からちょうど一三年前、悲劇的な謎の死をとげて当時たいそう有名になった(いや、今でもまだ人々の口にのぼる)この郡の地主、フョードル・パーヴロウィチ・カラマーゾフの三男であった。',
         'sentakusi1': 'ドストエフスキー「カラマーゾフの兄弟」',
         'sentakusi2': '小林多喜二「蟹工船」',
         'sentakusi3': '綿矢りさ「蹴りたい背中」',
         'sentakusi4': '住野よる「君の膵臓をたべたい」',
         'kotae': 'answer1',
         'ID' : 5,},
        {'daimei': '第６問',
         'mondai': '彼のことを、私と息子は博士と呼んだ。そして博士は息子を、ルートと呼んだ。息子の頭のてっぺんが、ルート記号のように平らだったからだ。',
         'sentakusi1': '小川洋子「博士の愛した数式」',
         'sentakusi2': '恩田陸「夜のピクニック」',
         'sentakusi3': 'ヘミングウェイ「老人と海」',
         'sentakusi4': '角田光代「八日目の蟬」',
         'kotae': 'answer1',
         'ID' : 6,},
        {'daimei': '第７問',
         'mondai': 'これは、私わたしが小さいときに、村の茂平もへいというおじいさんからきいたお話です。むかしは、私たちの村のちかくの、中山なかやまというところに小さなお城があって、中山さまというおとのさまが、おられたそうです。',
         'sentakusi1': '芥川龍之介「毛利先生」',
         'sentakusi2': '坂口安吾「堕落論」',
         'sentakusi3': '直木三十五「南国太平記」',
         'sentakusi4': '新美南吉「ごん狐」',
         'kotae': 'answer4',
         'ID' : 7,},
        {'daimei': '第８問',
         'mondai': '私は今年ことし三十九になる。人世じんせい五十が通相場とおりそうばなら、まだ今日明日きょうあす穴へ入ろうとも思わぬが、しかし未来は長いようでも短いものだ。',
         'sentakusi1': '樋口一葉「にごりえ」',
         'sentakusi2': '二葉亭四迷「平凡」',
         'sentakusi3': '宮沢賢治「セロ弾きのゴージュ」',
         'sentakusi4': '森鴎外「高瀬舟」',
         'kotae': 'answer2',
         'ID' : 8,},
        {'daimei': '第９問',
         'mondai': '――どうなるものか、この天地の大きな動きが。もう人間の個々の振舞いなどは、秋かぜの中の一片の木の葉でしかない。なるようになッてしまえ。',
         'sentakusi1': '東野圭吾「マスカレードシリーズ」',
         'sentakusi2': '宮部みゆき「火事」',
         'sentakusi3': '吉川英治「宮本武蔵 地の巻」',
         'sentakusi4': '伊坂幸太郎「ゴールデンスランバー」',
         'kotae': 'answer3',
         'ID' : 9,},
        {'daimei': '第１０問',
         'mondai': '私には、繰り返し見る夢がある。見ている最中は、夢だとはたぶん気づいていない。',
         'sentakusi1': '谷崎潤一郎「細雪」',
         'sentakusi2': '新海誠「すずめの戸締まり」',
         'sentakusi3': '佐倉まな「ごっこ」',
         'sentakusi4': 'ルイス・キャロル「不思議の国のアリス」',
         'kotae': 'answer2',
         'ID' : 10,},
    ]
    return render_template(
        'form.html',
        books=books
    )
@app.route('/second')
def second():
    books2 = [
        {'daimei': '第１問',
         'mondai': '親譲りの無鉄砲で子供の頃から損ばかりしている。',
         'sentakusi1': '夏目漱石「坊ちゃん」',
         'sentakusi2': '佐伯一麦「ア・ルース・ボーイ」',
         'sentakusi3': '古井由吉「杳子」',
         'sentakusi4': '和田はつ子「薬師」',
         'kotae': 'answer1',
         'ID': 1,}, 
        {'daimei': '第２問',
         'mondai': '「スプリットタンって知ってる？」',
         'sentakusi1': '宮下奈都「終わらない歌」',
         'sentakusi2': '越谷オサム「陽だまりの彼女」',
         'sentakusi3': '金原ひとみ「蛇にピアス」',
         'sentakusi4': '誉田哲也「ソウルケイジ」',
         'kotae': 'answer3',
         'ID' : 2,},
         {'daimei': '第３問',
         'mondai': '大地を震わす和太鼓の律動に、甲高くするどい笛が重なり響いていた。',
         'sentakusi1': '加納朋子「いちばん初めにあった海」',
         'sentakusi2': '又吉直樹「火花」',
         'sentakusi3': 'ミシェル・ビュトール「時間割」',
         'sentakusi4': 'ヘリベマルヲ「砒素と携帯、ロックンロール」',
         'kotae': 'answer2',
         'ID' : 3,},
         {'daimei': '第４問',
         'mondai': 'つくづく不思議な光景だと思う。',
         'sentakusi1': '吉田修一 「パレード」',
         'sentakusi2': '朝倉かすみ「田村はまだか」',
         'sentakusi3': '三島由紀夫「女神」',
         'sentakusi4': '町田康「くっすん大黒」',
         'kotae': 'answer1',
         'ID' : 4,},
         {'daimei': '第５問',
         'mondai': 'ああああああ',
         'sentakusi1': 'ランス・アームストロング「ただマイヨ・ジョーヌのためでなく」',
         'sentakusi2': '大槻あかね「あ」',
         'sentakusi3': '桐野夏生「ダーク」',
         'sentakusi4': '中山可穂「猫背の王子」',
         'kotae': 'answer2',
         'ID' : 5,},
         {'daimei': '第６問',
         'mondai': '子どもなんてみんな、試験管で作ればいい。',
         'sentakusi1': '小林多喜二「蟹工船」',
         'sentakusi2': '有川浩「レインツリーの国」',
         'sentakusi3': '湊かなえ「少女」',
         'sentakusi4': '梨木香歩「西の魔女が死んだ」',
         'kotae': 'answer3',
         'ID' : 6,},
         {'daimei': '第７問',
         'mondai': '木曾路はすべて山の中である。',
         'sentakusi1': '島崎藤村「夜明け前」',
         'sentakusi2': '乙一「平面いぬ。」',
         'sentakusi3': '酒見賢一「後宮小説」',
         'sentakusi4': '三崎亜記「となり町戦争」',
         'kotae': 'answer1',
         'ID' : 7,},
         {'daimei': '第８問',
         'mondai': '女の子のおちんちんは、お腹のなかについているの',
         'sentakusi1': '樺山三英「ジャン=ジャックの自意識の場合」',
         'sentakusi2': '円居挽「丸太町ルヴォワール」',
         'sentakusi3': '吉田健一「英国に就て」',
         'sentakusi4': '向田邦子「眠る盃」',
         'kotae': 'answer1',
         'ID' : 8,},
         {'daimei': '第９問',
         'mondai': 'まずコンパスが登場する。彼は気がくるっていた。',
         'sentakusi1': 'オスカー ワイルド「サロメ」',
         'sentakusi2': '司馬遼太郎「鬼謀の人」',
         'sentakusi3': '村上龍「イン ザ・ミソスープ」',
         'sentakusi4': '筒井康隆「虚航船団」',
         'kotae': 'answer4',
         'ID' : 9,},
         {'daimei': '第１０問',
         'mondai': 'ワタシ、日本文化大好きデス',
         'sentakusi1': '有川浩「塩の街」',
         'sentakusi2': 'グレアム グリーン「情事の終り」',
         'sentakusi3': '江國香織「雨はコーラがのめない」',
         'sentakusi4': '柳広司「ジョーカー・ゲーム」',
         'kotae': 'answer4',
         'ID' : 10,},
    ]
    return render_template(
        'second.html',
        books2=books2
    )
@app.route('/third')
def third():
    books3 = [
        {'daimei': '第１問',
         'mondai': '私がこの世でいちばん好きな場所は台所だと思う。',
         'sentakusi1': '吉本ばなな「キッチン」',
         'sentakusi2': '安部公房「砂の女」',
         'sentakusi3': '梶井基次郎「檸檬」',
         'sentakusi4': '綿矢りさ「蹴りたい背中」',
         'kotae': 'answer1',
         'ID': 1,}, 
        {'daimei': '第２問',
         'mondai': '居酒屋を始めるなら冬がいい──',
         'sentakusi1': '川村元気「億男」',
         'sentakusi2': '上橋菜穂子「鹿の王」',
         'sentakusi3': '秋川滝美「居酒屋ぼったくり」',
         'sentakusi4': '宮下奈都「羊と鋼の森」',
         'kotae': 'answer3',
         'ID' : 2,},
         {'daimei': '第３問',
         'mondai': 'かれは年をとっていた。メキシコ湾流に小舟を浮べ、ひとりで魚をとって日をおくっていたが、一匹も釣れない日が八十四日もつづいた。',
         'sentakusi1': '村田沙耶香「コンビニ人間」',
         'sentakusi2': '恩田陸「夜のピクニック」',
         'sentakusi3': '夏川草介「神様のカルテ」',
         'sentakusi4': 'ヘミングウェイ「老人と海」',
         'kotae': 'answer4',
         'ID' : 3,},
         {'daimei': '第４問',
         'mondai': '僕がまだ年若く、心に傷を負いやすかったころ、父親がひとつ忠告を与えてくれた。',
         'sentakusi1': '市川拓司「いま、会いにゆきます」',
         'sentakusi2': 'スコット・フィッツジェラルド「グレート・ギャツビー」',
         'sentakusi3': '角田光代「八日目の蟬」',
         'sentakusi4': 'リリー・フランキー「東京タワー」',
         'kotae': 'answer2',
         'ID' : 4,},
         {'daimei': '第５問',
         'mondai': '主役のための特別な通路などは設けられていない。',
         'sentakusi1': '阿部和重「アメリカの夜」',
         'sentakusi2': '遠藤周作「深い河」',
         'sentakusi3': '阿部和重「アメリカの夜」',
         'sentakusi4': '乾くるみ「セカンド・ラブ」',
         'kotae': 'answer4',
         'ID' : 5,},
         {'daimei': '第６問',
         'mondai': 'いまでは、チャールズ・ストリックランドの偉大さを否定する人などまずいない。',
         'sentakusi1': '古井由吉「杳子」',
         'sentakusi2': 'サマセット・モーム「月と六ペンス」',
         'sentakusi3': '友成純一「獣儀式 狂鬼降臨」',
         'sentakusi4': '島田雅彦「君が壊れてしまう前に」',
         'kotae': 'answer2',
         'ID' : 6,},
         {'daimei': '第７問',
         'mondai': '昔々あるところに、というくらい昔、せき止めにチミツシンという茶色い液体を飲まされた。',
         'sentakusi1': '佐野洋子「問題があります」',
         'sentakusi2': '長野まゆみ「螺子式少年」',
         'sentakusi3': '重松清「エイジ」',
         'sentakusi4': '京極夏彦「死ねばいいのに」',
         'kotae': 'answer1',
         'ID' : 7,},
         {'daimei': '第８問',
         'mondai': '名誉に価格なんてない。',
         'sentakusi1': '初野晴「千年ジュリエット」',
         'sentakusi2': '戸梶圭太「原子力宇宙船地球号」',
         'sentakusi3': '向田邦子「隣りの女」',
         'sentakusi4': '田中啓文「蹴りたい田中」',
         'kotae': 'answer1',
         'ID' : 8,},
         {'daimei': '第９問',
         'mondai': '雪はやんだ。',
         'sentakusi1': '伊坂幸太郎「オーデュボンの祈り」',
         'sentakusi2': '鈴木次郎「カスタム・チャイルド」',
         'sentakusi3': '古川日出男「ベルカ、吠えないのか?」',
         'sentakusi4': '西尾維新「ニンギョウがニンギョウ」',
         'kotae': 'answer3',
         'ID' : 9,},
         {'daimei': '第１０問',
         'mondai': '失業と離婚が同時だった。',
         'sentakusi1': '紺野キリフキ「はじめまして、本棚荘」',
         'sentakusi2': '椎名誠「ぱいかじ南海作戦」',
         'sentakusi3': '川上弘美「神様」',
         'sentakusi4': '日野裕太郎「スコシの領分」',
         'kotae': 'answer2',
         'ID' : 10,},       
    ]
    return render_template(
        'third.html',
        books3=books3
    )

@app.route('/fourth')
def fourth():
    books4 = [
        {'daimei': '第１問',
         'mondai': 'りんごは何色？',
         'sentakusi1': '赤色',
         'sentakusi2': '青色',
         'sentakusi3': '白色',
         'sentakusi4': '緑色',
         'kotae': 'answer3',
         'ID': 1,}, 
        {'daimei': '第２問',
         'mondai': 'メロスは激怒した。必ず、かの邪智暴虐の王を除かなければならぬと決意した。メロスには政治がわからぬ。',
         'sentakusi1': '湊かなえ「告白」',
         'sentakusi2': '太宰治「走れメロス」',
         'sentakusi3': '三島由紀夫「三島由紀夫レター教室」',
         'sentakusi4': '東野圭吾「秘密」',
         'kotae': 'answer2',
         'ID' : 2,},
         {'daimei': '第３問',
         'mondai': 'どっどど どどうど どどうど どどう 青いくるみも吹きとばせ すっぱいかりんも吹きとばせ どっどど どどうど どどうど どどう',
         'sentakusi1': '芥川龍之介「鼻」',
         'sentakusi2': '梶井基次郎「檸檬」',
         'sentakusi3': '中島敦「山月記」',
         'sentakusi4': '宮沢賢治「風の又三郎」',
         'kotae': 'answer4',
         'ID' : 3,},
         {'daimei': '第４問',
         'mondai': 'どっどど どどうど どどうど どどう 青いくるみも吹きとばせ すっぱいかりんも吹きとばせ どっどど どどうど どどうど どどう',
         'sentakusi1': '芥川龍之介「鼻」',
         'sentakusi2': '梶井基次郎「檸檬」',
         'sentakusi3': '中島敦「山月記」',
         'sentakusi4': '宮沢賢治「風の又三郎」',
         'kotae': 'answer4',
         'ID' : 3,},
         {'daimei': '第５問',
         'mondai': 'どっどど どどうど どどうど どどう 青いくるみも吹きとばせ すっぱいかりんも吹きとばせ どっどど どどうど どどうど どどう',
         'sentakusi1': '芥川龍之介「鼻」',
         'sentakusi2': '梶井基次郎「檸檬」',
         'sentakusi3': '中島敦「山月記」',
         'sentakusi4': '宮沢賢治「風の又三郎」',
         'kotae': 'answer4',
         'ID' : 3,},
         {'daimei': '第６問',
         'mondai': 'どっどど どどうど どどうど どどう 青いくるみも吹きとばせ すっぱいかりんも吹きとばせ どっどど どどうど どどうど どどう',
         'sentakusi1': '芥川龍之介「鼻」',
         'sentakusi2': '梶井基次郎「檸檬」',
         'sentakusi3': '中島敦「山月記」',
         'sentakusi4': '宮沢賢治「風の又三郎」',
         'kotae': 'answer4',
         'ID' : 3,},
         {'daimei': '第７問',
         'mondai': 'どっどど どどうど どどうど どどう 青いくるみも吹きとばせ すっぱいかりんも吹きとばせ どっどど どどうど どどうど どどう',
         'sentakusi1': '芥川龍之介「鼻」',
         'sentakusi2': '梶井基次郎「檸檬」',
         'sentakusi3': '中島敦「山月記」',
         'sentakusi4': '宮沢賢治「風の又三郎」',
         'kotae': 'answer4',
         'ID' : 3,},
         {'daimei': '第８問',
         'mondai': 'どっどど どどうど どどうど どどう 青いくるみも吹きとばせ すっぱいかりんも吹きとばせ どっどど どどうど どどうど どどう',
         'sentakusi1': '芥川龍之介「鼻」',
         'sentakusi2': '梶井基次郎「檸檬」',
         'sentakusi3': '中島敦「山月記」',
         'sentakusi4': '宮沢賢治「風の又三郎」',
         'kotae': 'answer4',
         'ID' : 3,},
         {'daimei': '第９問',
         'mondai': 'どっどど どどうど どどうど どどう 青いくるみも吹きとばせ すっぱいかりんも吹きとばせ どっどど どどうど どどうど どどう',
         'sentakusi1': '芥川龍之介「鼻」',
         'sentakusi2': '梶井基次郎「檸檬」',
         'sentakusi3': '中島敦「山月記」',
         'sentakusi4': '宮沢賢治「風の又三郎」',
         'kotae': 'answer4',
         'ID' : 3,},
         {'daimei': '第１０問',
         'mondai': 'どっどど どどうど どどうど どどう 青いくるみも吹きとばせ すっぱいかりんも吹きとばせ どっどど どどうど どどうど どどう',
         'sentakusi1': '芥川龍之介「鼻」',
         'sentakusi2': '梶井基次郎「檸檬」',
         'sentakusi3': '中島敦「山月記」',
         'sentakusi4': '宮沢賢治「風の又三郎」',
         'kotae': 'answer4',
         'ID' : 3,},       
    ]
    return render_template(
        'fourth.html',
        books4=books4
    )